//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KopkeHome_FMRS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KopkeHome_FMRS.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter confirm password.
        /// </summary>
        internal static string AlertEnterConfirmPassword {
            get {
                return ResourceManager.GetString("AlertEnterConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter New password.
        /// </summary>
        internal static string AlertEnterNewPassword {
            get {
                return ResourceManager.GetString("AlertEnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid password.
        /// </summary>
        internal static string AlertEnterValidPassword {
            get {
                return ResourceManager.GetString("AlertEnterValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter zip code.
        /// </summary>
        internal static string AlertEnterZip {
            get {
                return ResourceManager.GetString("AlertEnterZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirm password should be same.
        /// </summary>
        internal static string AlertNewPasswordConfirmSame {
            get {
                return ResourceManager.GetString("AlertNewPasswordConfirmSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No zipcode found..
        /// </summary>
        internal static string AlertNoZipCodeFound {
            get {
                return ResourceManager.GetString("AlertNoZipCodeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string ConstantFalse {
            get {
                return ResourceManager.GetString("ConstantFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string ConstantTrue {
            get {
                return ResourceManager.GetString("ConstantTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string DigitTwo {
            get {
                return ResourceManager.GetString("DigitTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string DigitZero {
            get {
                return ResourceManager.GetString("DigitZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string DisitOne {
            get {
                return ResourceManager.GetString("DisitOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to log out.
        /// </summary>
        internal static string DoYouWantlogOut {
            get {
                return ResourceManager.GetString("DoYouWantlogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete account.
        /// </summary>
        internal static string DoYouWantToDeleteAccount {
            get {
                return ResourceManager.GetString("DoYouWantToDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string Forgot_Password_ {
            get {
                return ResourceManager.GetString("Forgot Password?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgotPassword_ {
            get {
                return ResourceManager.GetString("ForgotPassword?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gjghjgh {
            get {
                return ResourceManager.GetString("gjghjgh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go English.
        /// </summary>
        internal static string GoEnglish {
            get {
                return ResourceManager.GetString("GoEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Spanish.
        /// </summary>
        internal static string GoSpanish {
            get {
                return ResourceManager.GetString("GoSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credential!.
        /// </summary>
        internal static string InvalidCredential {
            get {
                return ResourceManager.GetString("InvalidCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address and password to access your account.
        /// </summary>
        internal static string LoginPageHeaderText {
            get {
                return ResourceManager.GetString("LoginPageHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed successfully.
        /// </summary>
        internal static string PasswordChangeSuccesfulMessage {
            get {
                return ResourceManager.GetString("PasswordChangeSuccesfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email id.
        /// </summary>
        internal static string PleaseEnterEmailId {
            get {
                return ResourceManager.GetString("PleaseEnterEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Password.
        /// </summary>
        internal static string PleaseEnterPassword {
            get {
                return ResourceManager.GetString("PleaseEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusChanged.
        /// </summary>
        internal static string SatatusChangesMessaging {
            get {
                return ResourceManager.GetString("SatatusChangesMessaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select zipcode first!.
        /// </summary>
        internal static string SelectZipCode {
            get {
                return ResourceManager.GetString("SelectZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Changed Successfully.
        /// </summary>
        internal static string StatusChangedSuccessfully {
            get {
                return ResourceManager.GetString("StatusChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credential!.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email id.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have 24 hour phone answering?.
        /// </summary>
        internal static string txt24HourPhoneCall {
            get {
                return ResourceManager.GetString("txt24HourPhoneCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        internal static string txtAccountType {
            get {
                return ResourceManager.GetString("txtAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type :.
        /// </summary>
        internal static string txtAccountType_ {
            get {
                return ResourceManager.GetString("txtAccountType:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Status:.
        /// </summary>
        internal static string txtAccoutStatus {
            get {
                return ResourceManager.GetString("txtAccoutStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address :.
        /// </summary>
        internal static string txtAddress__ {
            get {
                return ResourceManager.GetString("txtAddress :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have someone to answer the phone during normal business hours?.
        /// </summary>
        internal static string txtAnswerCallBusinesshour {
            get {
                return ResourceManager.GetString("txtAnswerCallBusinesshour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        internal static string txtBasicInformation {
            get {
                return ResourceManager.GetString("txtBasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking for Later(17-52 weeks.
        /// </summary>
        internal static string txtBookingForLater {
            get {
                return ResourceManager.GetString("txtBookingForLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking for Now(0-4 weeks).
        /// </summary>
        internal static string txtBookingForNow {
            get {
                return ResourceManager.GetString("txtBookingForNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking for Soon(5-16 weeks).
        /// </summary>
        internal static string txtBookingForSoon {
            get {
                return ResourceManager.GetString("txtBookingForSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Address.
        /// </summary>
        internal static string txtBusinessAddress {
            get {
                return ResourceManager.GetString("txtBusinessAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Description.
        /// </summary>
        internal static string txtBusinessDescription {
            get {
                return ResourceManager.GetString("txtBusinessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Information.
        /// </summary>
        internal static string txtBusinessInformation {
            get {
                return ResourceManager.GetString("txtBusinessInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        internal static string txtBusinessName {
            get {
                return ResourceManager.GetString("txtBusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business or trade license(s) :.
        /// </summary>
        internal static string txtBusinessOrtradelicense_ {
            get {
                return ResourceManager.GetString("txtBusinessOrtradelicense:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business or Trade License :.
        /// </summary>
        internal static string txtBusinessOrTradeLicense__ {
            get {
                return ResourceManager.GetString("txtBusinessOrTradeLicense :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business or Trade License :.
        /// </summary>
        internal static string txtBusinessOrTradeLicense_66 {
            get {
                return ResourceManager.GetString("txtBusinessOrTradeLicense:66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a business or trade license(s)?.
        /// </summary>
        internal static string txtBusinessTradeLicense {
            get {
                return ResourceManager.GetString("txtBusinessTradeLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business URL.
        /// </summary>
        internal static string txtBusinessURL {
            get {
                return ResourceManager.GetString("txtBusinessURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Contractors? :.
        /// </summary>
        internal static string txtByOtherContractor {
            get {
                return ResourceManager.GetString("txtByOtherContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string txtCamera {
            get {
                return ResourceManager.GetString("txtCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash :.
        /// </summary>
        internal static string txtCash {
            get {
                return ResourceManager.GetString("txtCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string txtCategories {
            get {
                return ResourceManager.GetString("txtCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name :.
        /// </summary>
        internal static string txtCategoryName {
            get {
                return ResourceManager.GetString("txtCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Change Work Status.
        /// </summary>
        internal static string txtChangeWorkStatus {
            get {
                return ResourceManager.GetString("txtChangeWorkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your work status.
        /// </summary>
        internal static string txtChangeYourWorkStatus {
            get {
                return ResourceManager.GetString("txtChangeYourWorkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name.
        /// </summary>
        internal static string txtCityName {
            get {
                return ResourceManager.GetString("txtCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Office :.
        /// </summary>
        internal static string txtCommercialOffice_ {
            get {
                return ResourceManager.GetString("txtCommercialOffice:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name :.
        /// </summary>
        internal static string txtCompanyName__ {
            get {
                return ResourceManager.GetString("txtCompanyName :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have Workman’s Compensation Insurance?.
        /// </summary>
        internal static string txtCompensationInsurance {
            get {
                return ResourceManager.GetString("txtCompensationInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string txtConfirmPassword {
            get {
                return ResourceManager.GetString("txtConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to be contacted directly by Other Contractors?.
        /// </summary>
        internal static string txtContactectDirectlyContractor {
            get {
                return ResourceManager.GetString("txtContactectDirectlyContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to be contacted directly by Homeowners?.
        /// </summary>
        internal static string txtContactectDirectlyHomrOwner {
            get {
                return ResourceManager.GetString("txtContactectDirectlyHomrOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor List.
        /// </summary>
        internal static string txtContractorList {
            get {
                return ResourceManager.GetString("txtContractorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor Type :.
        /// </summary>
        internal static string txtContractorType {
            get {
                return ResourceManager.GetString("txtContractorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREDENTIALS.
        /// </summary>
        internal static string txtCREDENTIALS {
            get {
                return ResourceManager.GetString("txtCREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Cards :.
        /// </summary>
        internal static string txtCreditCards {
            get {
                return ResourceManager.GetString("txtCreditCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT PLAN.
        /// </summary>
        internal static string txtCURRENTPLAN {
            get {
                return ResourceManager.GetString("txtCURRENTPLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current work status:.
        /// </summary>
        internal static string txtCurrentWorkStatus_ {
            get {
                return ResourceManager.GetString("txtCurrentWorkStatus:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        internal static string txtDeleteAccount {
            get {
                return ResourceManager.GetString("txtDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Fee :.
        /// </summary>
        internal static string txtDesignFee_ {
            get {
                return ResourceManager.GetString("txtDesignFee:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOING BUSINESS.
        /// </summary>
        internal static string txtDOINGBUSINESS {
            get {
                return ResourceManager.GetString("txtDOINGBUSINESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want to Change the Language.
        /// </summary>
        internal static string txtDoYouWantChangeLanguage {
            get {
                return ResourceManager.GetString("txtDoYouWantChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User Profile.
        /// </summary>
        internal static string txtEditUserProfile {
            get {
                return ResourceManager.GetString("txtEditUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string txtEmailAddress {
            get {
                return ResourceManager.GetString("txtEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address :.
        /// </summary>
        internal static string txtEmailAddress_ {
            get {
                return ResourceManager.GetString("txtEmailAddress:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you offer emergency services?.
        /// </summary>
        internal static string txtEmergencyService {
            get {
                return ResourceManager.GetString("txtEmergencyService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Services :.
        /// </summary>
        internal static string txtEmergencyServices_ {
            get {
                return ResourceManager.GetString("txtEmergencyServices:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate Fee :.
        /// </summary>
        internal static string txtEstimateFee_ {
            get {
                return ResourceManager.GetString("txtEstimateFee:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook :.
        /// </summary>
        internal static string txtFacebook_ {
            get {
                return ResourceManager.GetString("txtFacebook:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string txtFirstName {
            get {
                return ResourceManager.GetString("txtFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you give “Free Estimates?.
        /// </summary>
        internal static string txtFreeEstimate {
            get {
                return ResourceManager.GetString("txtFreeEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string txtGallery {
            get {
                return ResourceManager.GetString("txtGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give Free Estimates? :.
        /// </summary>
        internal static string txtGiveFreeEstimates {
            get {
                return ResourceManager.GetString("txtGiveFreeEstimates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Home.
        /// </summary>
        internal static string txtHome {
            get {
                return ResourceManager.GetString("txtHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home owners? :.
        /// </summary>
        internal static string txtHomeOwners_ {
            get {
                return ResourceManager.GetString("txtHomeOwners:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many job site crews do you have?.
        /// </summary>
        internal static string txtJobSiteCrew {
            get {
                return ResourceManager.GetString("txtJobSiteCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Language.
        /// </summary>
        internal static string txtLanguage {
            get {
                return ResourceManager.GetString("txtLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string txtLastName {
            get {
                return ResourceManager.GetString("txtLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated :.
        /// </summary>
        internal static string txtLastUpdated_ {
            get {
                return ResourceManager.GetString("txtLastUpdated:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liability Insurance File :.
        /// </summary>
        internal static string txtLiabilityDoc {
            get {
                return ResourceManager.GetString("txtLiabilityDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liability Insurance :.
        /// </summary>
        internal static string txtLiabilityInsurance_ {
            get {
                return ResourceManager.GetString("txtLiabilityInsurance:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have Liability Insurance?.
        /// </summary>
        internal static string txtLiabilityIsurance {
            get {
                return ResourceManager.GetString("txtLiabilityIsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a commercial location where Other Contractors can meet with you?.
        /// </summary>
        internal static string txtLoctionDescriptionForContact {
            get {
                return ResourceManager.GetString("txtLoctionDescriptionForContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Logout.
        /// </summary>
        internal static string txtLogout {
            get {
                return ResourceManager.GetString("txtLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member ID:.
        /// </summary>
        internal static string txtMemberID_ {
            get {
                return ResourceManager.GetString("txtMemberID:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Benefit.
        /// </summary>
        internal static string txtMembershipBenefit {
            get {
                return ResourceManager.GetString("txtMembershipBenefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right now this service is not available on the zip code.
        /// </summary>
        internal static string txtMessageNowServiceNotAvailble {
            get {
                return ResourceManager.GetString("txtMessageNowServiceNotAvailble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile App.
        /// </summary>
        internal static string txtMobileApp {
            get {
                return ResourceManager.GetString("txtMobileApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Profile.
        /// </summary>
        internal static string txtMyProfile {
            get {
                return ResourceManager.GetString("txtMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string txtNewPassword {
            get {
                return ResourceManager.GetString("txtNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are your normal business hours?.
        /// </summary>
        internal static string txtNormalBusinessHour {
            get {
                return ResourceManager.GetString("txtNormalBusinessHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        internal static string txtNotAvailable {
            get {
                return ResourceManager.GetString("txtNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Verified.
        /// </summary>
        internal static string txtNotVerified {
            get {
                return ResourceManager.GetString("txtNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Employees :.
        /// </summary>
        internal static string txtNumberEmployees_ {
            get {
                return ResourceManager.GetString("txtNumberEmployees:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Crews :.
        /// </summary>
        internal static string txtNumberOfCrews_ {
            get {
                return ResourceManager.GetString("txtNumberOfCrews:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Employee.
        /// </summary>
        internal static string txtNumberofEmployee {
            get {
                return ResourceManager.GetString("txtNumberofEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you offer design services?.
        /// </summary>
        internal static string txtOfferDesignService {
            get {
                return ResourceManager.GetString("txtOfferDesignService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers Design Services ? :.
        /// </summary>
        internal static string txtOffersDesignServices_ {
            get {
                return ResourceManager.GetString("txtOffersDesignServices:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Accepted :.
        /// </summary>
        internal static string txtPaymentAccepted_ {
            get {
                return ResourceManager.GetString("txtPaymentAccepted:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment App Name :.
        /// </summary>
        internal static string txtPaymentAppName_ {
            get {
                return ResourceManager.GetString("txtPaymentAppName:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment App Name :.
        /// </summary>
        internal static string txtPaymentAppName__ {
            get {
                return ResourceManager.GetString("txtPaymentAppName :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Apps :.
        /// </summary>
        internal static string txtPaymentApps_ {
            get {
                return ResourceManager.GetString("txtPaymentApps:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Informtion.
        /// </summary>
        internal static string txtPaymentInformtion {
            get {
                return ResourceManager.GetString("txtPaymentInformtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Cheque :.
        /// </summary>
        internal static string txtPersonalCheck_ {
            get {
                return ResourceManager.GetString("txtPersonalCheck:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Checks.
        /// </summary>
        internal static string txtPersonalChecks {
            get {
                return ResourceManager.GetString("txtPersonalChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number :.
        /// </summary>
        internal static string txtPhoneNumber_ {
            get {
                return ResourceManager.GetString("txtPhoneNumber:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        internal static string txtPhoneNumber_Mobile_ {
            get {
                return ResourceManager.GetString("txtPhoneNumber(Mobile)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office number.
        /// </summary>
        internal static string txtPhoneNumber_Office_ {
            get {
                return ResourceManager.GetString("txtPhoneNumber(Office)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Number.
        /// </summary>
        internal static string txtPhoneOffice_ {
            get {
                return ResourceManager.GetString("txtPhoneOffice:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter category.
        /// </summary>
        internal static string txtPleaseEnterCategory {
            get {
                return ResourceManager.GetString("txtPleaseEnterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Successfully Updated.
        /// </summary>
        internal static string txtProfileSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("txtProfileSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string txtResetPassword {
            get {
                return ResourceManager.GetString("txtResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string txtSave {
            get {
                return ResourceManager.GetString("txtSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Now.
        /// </summary>
        internal static string txtSearchNow {
            get {
                return ResourceManager.GetString("txtSearchNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string txtSelectLanguage {
            get {
                return ResourceManager.GetString("txtSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select any option.
        /// </summary>
        internal static string txtSelectWorkStatusOption {
            get {
                return ResourceManager.GetString("txtSelectWorkStatusOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select zipcode first!.
        /// </summary>
        internal static string txtSelectZipCode {
            get {
                return ResourceManager.GetString("txtSelectZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Request.
        /// </summary>
        internal static string txtSendRequest {
            get {
                return ResourceManager.GetString("txtSendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Categories.
        /// </summary>
        internal static string txtServiceCategories {
            get {
                return ResourceManager.GetString("txtServiceCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICES OFFERED.
        /// </summary>
        internal static string txtSERVICESOFFERED {
            get {
                return ResourceManager.GetString("txtSERVICESOFFERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Zip Codes.
        /// </summary>
        internal static string txtServiceZipCodes {
            get {
                return ResourceManager.GetString("txtServiceZipCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Name.
        /// </summary>
        internal static string txtStateName {
            get {
                return ResourceManager.GetString("txtStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status :.
        /// </summary>
        internal static string txtStatus {
            get {
                return ResourceManager.GetString("txtStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string txtSubmit {
            get {
                return ResourceManager.GetString("txtSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time :.
        /// </summary>
        internal static string txtTime_ {
            get {
                return ResourceManager.GetString("txtTime:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of work want to get done?.
        /// </summary>
        internal static string txtTypeofWorkWant {
            get {
                return ResourceManager.GetString("txtTypeofWorkWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Member ID.
        /// </summary>
        internal static string txtUniqueMemberID {
            get {
                return ResourceManager.GetString("txtUniqueMemberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string txtUpdate {
            get {
                return ResourceManager.GetString("txtUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        internal static string txtUserProfile {
            get {
                return ResourceManager.GetString("txtUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        internal static string txtVerified {
            get {
                return ResourceManager.GetString("txtVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string txtVersion_ {
            get {
                return ResourceManager.GetString("txtVersion:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   View Business Profile.
        /// </summary>
        internal static string txtViewBusinessProfile {
            get {
                return ResourceManager.GetString("txtViewBusinessProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        internal static string txtViewDetails {
            get {
                return ResourceManager.GetString("txtViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   View Membership Plan.
        /// </summary>
        internal static string txtViewMembershipPlan {
            get {
                return ResourceManager.GetString("txtViewMembershipPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to be contacted directly by  .
        /// </summary>
        internal static string txtWanttoContactedDirectlyby {
            get {
                return ResourceManager.GetString("txtWanttoContactedDirectlyby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string txtWebsite {
            get {
                return ResourceManager.GetString("txtWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website :.
        /// </summary>
        internal static string txtWebsite_ {
            get {
                return ResourceManager.GetString("txtWebsite:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workman&apos;s Compensation Insurance :.
        /// </summary>
        internal static string txtWorkmanCompensationInsurance_ {
            get {
                return ResourceManager.GetString("txtWorkmanCompensationInsurance:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workman&apos;s Compensation Insurance File :.
        /// </summary>
        internal static string txtWorkmanCompensationInsuranceFile_ {
            get {
                return ResourceManager.GetString("txtWorkmanCompensationInsuranceFile:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workman&apos;s Compensation Insurance File :.
        /// </summary>
        internal static string txtWorkmanDoc {
            get {
                return ResourceManager.GetString("txtWorkmanDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Status.
        /// </summary>
        internal static string txtWorkStatus {
            get {
                return ResourceManager.GetString("txtWorkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year in Business.
        /// </summary>
        internal static string txtYearInBusiness {
            get {
                return ResourceManager.GetString("txtYearInBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years In Business :.
        /// </summary>
        internal static string txtYearInBusiness_ {
            get {
                return ResourceManager.GetString("txtYearInBusiness:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Documents.
        /// </summary>
        internal static string txtYourDocuments {
            get {
                return ResourceManager.GetString("txtYourDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Experience History :.
        /// </summary>
        internal static string txtYourExperienceHistory {
            get {
                return ResourceManager.GetString("txtYourExperienceHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string txtZipCode {
            get {
                return ResourceManager.GetString("txtZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP CODE SERVED.
        /// </summary>
        internal static string txtZIPCODESERVED {
            get {
                return ResourceManager.GetString("txtZIPCODESERVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email id.
        /// </summary>
        internal static string ValidEmailError {
            get {
                return ResourceManager.GetString("ValidEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
