//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KopkeHome_FMRS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFileEnglish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFileEnglish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KopkeHome_FMRS.Resources.ResourceFileEnglish", typeof(ResourceFileEnglish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter confirm password.
        /// </summary>
        internal static string AlertEnterConfirmPassword {
            get {
                return ResourceManager.GetString("AlertEnterConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter New password.
        /// </summary>
        internal static string AlertEnterNewPassword {
            get {
                return ResourceManager.GetString("AlertEnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid password.
        /// </summary>
        internal static string AlertEnterValidPassword {
            get {
                return ResourceManager.GetString("AlertEnterValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter zip code.
        /// </summary>
        internal static string AlertEnterZip {
            get {
                return ResourceManager.GetString("AlertEnterZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirm password should be same.
        /// </summary>
        internal static string AlertNewPasswordConfirmSame {
            get {
                return ResourceManager.GetString("AlertNewPasswordConfirmSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No zipcode found..
        /// </summary>
        internal static string AlertNoZipCodeFound {
            get {
                return ResourceManager.GetString("AlertNoZipCodeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string ConstantFalse {
            get {
                return ResourceManager.GetString("ConstantFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string ConstantTrue {
            get {
                return ResourceManager.GetString("ConstantTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string DigitTwo {
            get {
                return ResourceManager.GetString("DigitTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string DigitZero {
            get {
                return ResourceManager.GetString("DigitZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string DisitOne {
            get {
                return ResourceManager.GetString("DisitOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to log ou.
        /// </summary>
        internal static string DoYouWantlogOut {
            get {
                return ResourceManager.GetString("DoYouWantlogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete account.
        /// </summary>
        internal static string DoYouWantToDeleteAccount {
            get {
                return ResourceManager.GetString("DoYouWantToDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credential!.
        /// </summary>
        internal static string InvalidCredential {
            get {
                return ResourceManager.GetString("InvalidCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right now this service is not available on the zip code.
        /// </summary>
        internal static string messageNowServiceNotAvailble {
            get {
                return ResourceManager.GetString("messageNowServiceNotAvailble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed successfully.
        /// </summary>
        internal static string PasswordChangeSuccesfulMessage {
            get {
                return ResourceManager.GetString("PasswordChangeSuccesfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email id.
        /// </summary>
        internal static string PleaseEnterEmailId {
            get {
                return ResourceManager.GetString("PleaseEnterEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusChanged.
        /// </summary>
        internal static string SatatusChangesMessaging {
            get {
                return ResourceManager.GetString("SatatusChangesMessaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select any option.
        /// </summary>
        internal static string SelectWorkStatusOption {
            get {
                return ResourceManager.GetString("SelectWorkStatusOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select zipcode first!.
        /// </summary>
        internal static string SelectZipCode {
            get {
                return ResourceManager.GetString("SelectZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Changed Successfully.
        /// </summary>
        internal static string StatusChangedSuccessfully {
            get {
                return ResourceManager.GetString("StatusChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Verified.
        /// </summary>
        internal static string txtNotVerified {
            get {
                return ResourceManager.GetString("txtNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        internal static string txtVerified {
            get {
                return ResourceManager.GetString("txtVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email id.
        /// </summary>
        internal static string ValidEmailError {
            get {
                return ResourceManager.GetString("ValidEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
