//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KopkeHome_FMRS_API.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KopkeHome_FMRS_API.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Already Registered.
        /// </summary>
        public static string ALREADY_REG {
            get {
                return ResourceManager.GetString("ALREADY_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancele {
            get {
                return ResourceManager.GetString("Cancele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html lang=&quot;en-US&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta content=&quot;text/html; charset=utf-8&quot; http-equiv=&quot;Content-Type&quot; /&gt;
        ///    &lt;title&gt;Reset Password Email Template&lt;/title&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;Reset Password Email Template.&quot;&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        @import url(&apos;https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&amp;display=swap&apos;);
        ///        body {
        ///            font-family: &apos;Poppins&apos;, sans-serif;
        ///        }
        ///        a:hover {
        ///            text-decoration [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CustomMembershipHtml {
            get {
                return ResourceManager.GetString("CustomMembershipHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your custom plan created successfully..
        /// </summary>
        public static string CustomMembershipPlanEmailHeader {
            get {
                return ResourceManager.GetString("CustomMembershipPlanEmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved successfully..
        /// </summary>
        public static string DataSaved {
            get {
                return ResourceManager.GetString("DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data updated successfully..
        /// </summary>
        public static string DataUpdated {
            get {
                return ResourceManager.GetString("DataUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not registered with Prohz..
        /// </summary>
        public static string EmailIsNotRegistered {
            get {
                return ResourceManager.GetString("EmailIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed..
        /// </summary>
        public static string FailureMsg {
            get {
                return ResourceManager.GetString("FailureMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow URL to make payment..
        /// </summary>
        public static string FollowUrl {
            get {
                return ResourceManager.GetString("FollowUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change password at the moment, Please try again later.
        /// </summary>
        public static string ForgotPasswordFailureMsg {
            get {
                return ResourceManager.GetString("ForgotPasswordFailureMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Send mail at the moment, Please try again later..
        /// </summary>
        public static string ForgotPasswordLinkFailureMsg {
            get {
                return ResourceManager.GetString("ForgotPasswordLinkFailureMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent!, Please check your mail..
        /// </summary>
        public static string ForgotPasswordLinkSuccessMsg {
            get {
                return ResourceManager.GetString("ForgotPasswordLinkSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password reset link..
        /// </summary>
        public static string ForgotPasswordResetLinkSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordResetLinkSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully!.
        /// </summary>
        public static string ForgotPasswordSuccessMsg {
            get {
                return ResourceManager.GetString("ForgotPasswordSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html lang=&quot;en-US&quot;&gt;&lt;head&gt;
        ///    &lt;meta content=&quot;text/html; charset=utf-8&quot; http-equiv=&quot;Content-Type&quot; /&gt;
        ///    &lt;title&gt;Reset Password Email Template&lt;/title&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;Reset Password Email Template.&quot;&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        @import url(&apos;https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&amp;display=swap&apos;);
        ///        body {
        ///            font-family: &apos;Poppins&apos;, sans-serif;
        ///        }
        ///        a:hover {
        ///            text-decoration: un [rest of string was truncated]&quot;;.
        /// </summary>
        public static string html {
            get {
                return ResourceManager.GetString("html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http Status code does not found.
        /// </summary>
        public static string HttpStatusCode {
            get {
                return ResourceManager.GetString("HttpStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model is not valid!.
        /// </summary>
        public static string InvalidModel {
            get {
                return ResourceManager.GetString("InvalidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user!.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already subscribed..
        /// </summary>
        public static string isSubscribed {
            get {
                return ResourceManager.GetString("isSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User don&apos;t have any subscription..
        /// </summary>
        public static string IsSubscription {
            get {
                return ResourceManager.GetString("IsSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 10 Contractors Available on this zipcode..
        /// </summary>
        public static string Less10No {
            get {
                return ResourceManager.GetString("Less10No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You selected silver plan so can&apos;t use mobile app try on Web.
        /// </summary>
        public static string Messase_LoginR {
            get {
                return ResourceManager.GetString("Messase_LoginR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 10 Contractors Available.
        /// </summary>
        public static string More10No {
            get {
                return ResourceManager.GetString("More10No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found.
        /// </summary>
        public static string NOT_FOUND {
            get {
                return ResourceManager.GetString("NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Change Password!.
        /// </summary>
        public static string PasswordChangedFaild {
            get {
                return ResourceManager.GetString("PasswordChangedFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed Successfully!.
        /// </summary>
        public static string PasswordChangedSuccess {
            get {
                return ResourceManager.GetString("PasswordChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user not found.Please register yourself..
        /// </summary>
        public static string RegisterYourself {
            get {
                return ResourceManager.GetString("RegisterYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the verification code sent on you email.
        /// </summary>
        public static string REGS_SUCCESS {
            get {
                return ResourceManager.GetString("REGS_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved!.
        /// </summary>
        public static string SavedMsg {
            get {
                return ResourceManager.GetString("SavedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already have a subscription..
        /// </summary>
        public static string SubscriptionMsg {
            get {
                return ResourceManager.GetString("SubscriptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered successfully.
        /// </summary>
        public static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessMsg {
            get {
                return ResourceManager.GetString("SuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted successfully.
        /// </summary>
        public static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not deleted.
        /// </summary>
        public static string UserIsDelete {
            get {
                return ResourceManager.GetString("UserIsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id or password is incorrect..
        /// </summary>
        public static string UserOrPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("UserOrPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid user!.
        /// </summary>
        public static string ValidUser {
            get {
                return ResourceManager.GetString("ValidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Successfully Completed.
        /// </summary>
        public static string VER_SUCCESS {
            get {
                return ResourceManager.GetString("VER_SUCCESS", resourceCulture);
            }
        }
    }
}
