//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KopkeHome_UtilityLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KopkeHome_UtilityLayer.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category deleted successfully.
        /// </summary>
        public static string CategoryDelete {
            get {
                return ResourceManager.GetString("CategoryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category inserted successfully.
        /// </summary>
        public static string CategoryInsert {
            get {
                return ResourceManager.GetString("CategoryInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Updated successfully.
        /// </summary>
        public static string CategoryUpdate {
            get {
                return ResourceManager.GetString("CategoryUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category already exist.
        /// </summary>
        public static string CheckCategory {
            get {
                return ResourceManager.GetString("CheckCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already exists..
        /// </summary>
        public static string EmailAlreadyExist {
            get {
                return ResourceManager.GetString("EmailAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password do not match.
        /// </summary>
        public static string EmailOrPasswordInvalid {
            get {
                return ResourceManager.GetString("EmailOrPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ inserted successfully.
        /// </summary>
        public static string Faq {
            get {
                return ResourceManager.GetString("Faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ deleted successfully.
        /// </summary>
        public static string FaqDelete {
            get {
                return ResourceManager.GetString("FaqDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ Updated successfully.
        /// </summary>
        public static string FaqUpdate {
            get {
                return ResourceManager.GetString("FaqUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Video deleted successfully.
        /// </summary>
        public static string PromoDelete {
            get {
                return ResourceManager.GetString("PromoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Video inserted successfully.
        /// </summary>
        public static string PromoInsert {
            get {
                return ResourceManager.GetString("PromoInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Video Updated successfully.
        /// </summary>
        public static string PromoUpdate {
            get {
                return ResourceManager.GetString("PromoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP is wrong..
        /// </summary>
        public static string WrongOTP {
            get {
                return ResourceManager.GetString("WrongOTP", resourceCulture);
            }
        }
    }
}
