name: Deploy KopkeHome

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 76.13.24.232
          username: developer
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |

            echo ">>> Starting deployment"

            # Go to repo
            cd ~/Prohz || exit 1

            git pull origin main

            echo ">>> Publishing Backend"
            cd KopkeHome-FMRS_API || exit 1
            dotnet publish -c Release -o /home/developer/publish/backend

            echo ">>> Restart API"
            sudo systemctl restart kopke-api

            echo ">>> Publishing Frontend"
            cd ../KopkeHome-WebApp || exit 1
            dotnet publish -c Release -o /home/developer/publish/frontend

            echo ">>> Restart Web"
            sudo systemctl restart kopke-web

            echo ">>> Deployment completed"